// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardNumericController from "./dashboard_numeric_controller"
application.register("dashboard-numeric", DashboardNumericController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertgoalsController from "./insertgoals_controller"
application.register("insertgoals", InsertgoalsController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import ProgressbarController from "./progressbar_controller"
application.register("progressbar", ProgressbarController)
